--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

-- Started on 2026-02-28 16:05:04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 24596)
-- Name: asta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.asta (
    "idAsta" integer NOT NULL,
    acquirente character varying(255) NOT NULL,
    fine bigint NOT NULL,
    "idImmobile" integer NOT NULL,
    prezzo_attuale double precision NOT NULL,
    prezzo_orig double precision NOT NULL
);


--
-- TOC entry 213 (class 1259 OID 24595)
-- Name: asta_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.asta ALTER COLUMN "idAsta" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 24610)
-- Name: immagine; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.immagine (
    "idImmagine" integer NOT NULL,
    immagine character varying(255) NOT NULL,
    "idImmobile" integer NOT NULL
);


--
-- TOC entry 217 (class 1259 OID 24609)
-- Name: immagine_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.immagine ALTER COLUMN "idImmagine" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.immagine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 24588)
-- Name: immobile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.immobile (
    "idImmobile" integer NOT NULL,
    descrizione character varying(1000),
    indirizzo character varying(255) NOT NULL,
    metri_quadri double precision NOT NULL,
    nome character varying(255) NOT NULL,
    prezzo_attuale double precision NOT NULL,
    prezzo_orig double precision NOT NULL,
    proprietario character varying(255) NOT NULL,
    "tipoImmobile" character varying(255) NOT NULL,
    tipo_annuncio character varying(255) NOT NULL
);


--
-- TOC entry 211 (class 1259 OID 24587)
-- Name: immobile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.immobile ALTER COLUMN "idImmobile" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.immobile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 24602)
-- Name: recensione; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recensione (
    "idRecensione" integer NOT NULL,
    "idUtente" integer NOT NULL,
    valutazione smallint NOT NULL,
    titolo character varying(255) NOT NULL,
    "idImmobile" integer
);


--
-- TOC entry 215 (class 1259 OID 24601)
-- Name: recensione_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recensione ALTER COLUMN "idRecensione" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recensione_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 24578)
-- Name: utente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.utente (
    "idUtente" integer NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    ruolo character varying(255) NOT NULL,
    cognome character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    telefono character varying(255) NOT NULL,
    bannato boolean DEFAULT false
);


--
-- TOC entry 209 (class 1259 OID 24577)
-- Name: utente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.utente ALTER COLUMN "idUtente" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3341 (class 0 OID 24596)
-- Dependencies: 214
-- Data for Name: asta; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 3345 (class 0 OID 24610)
-- Dependencies: 218
-- Data for Name: immagine; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.immagine ("idImmagine", immagine, "idImmobile") VALUES (1, 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 1);
INSERT INTO public.immagine ("idImmagine", immagine, "idImmobile") VALUES (2, 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 1);
INSERT INTO public.immagine ("idImmagine", immagine, "idImmobile") VALUES (3, 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 2);
INSERT INTO public.immagine ("idImmagine", immagine, "idImmobile") VALUES (4, 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 3);
INSERT INTO public.immagine ("idImmagine", immagine, "idImmobile") VALUES (5, 'https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 4);
INSERT INTO public.immagine ("idImmagine", immagine, "idImmobile") VALUES (6, 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 5);
INSERT INTO public.immagine ("idImmagine", immagine, "idImmobile") VALUES (7, 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 6);
INSERT INTO public.immagine ("idImmagine", immagine, "idImmobile") VALUES (8, 'https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 6);


--
-- TOC entry 3339 (class 0 OID 24588)
-- Dependencies: 212
-- Data for Name: immobile; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.immobile ("idImmobile", descrizione, indirizzo, metri_quadri, nome, prezzo_attuale, prezzo_orig, proprietario, "tipoImmobile", tipo_annuncio) VALUES (1, 'Splendido attico in centro città con vista mozzafiato.', 'Via Roma 15, Milano', 120, 'Attico Panoramico Centro', 430000, 450000, 'Mario Rossi', 'Appartamento', 'VENDITA');
INSERT INTO public.immobile ("idImmobile", descrizione, indirizzo, metri_quadri, nome, prezzo_attuale, prezzo_orig, proprietario, "tipoImmobile", tipo_annuncio) VALUES (2, 'Lussuosa villa disposta su tre livelli. Ampio giardino e piscina.', 'Via dei Pini 42, Como', 350, 'Villa con Piscina Privata', 1200000, 1200000, 'Mario Rossi', 'Villa', 'VENDITA');
INSERT INTO public.immobile ("idImmobile", descrizione, indirizzo, metri_quadri, nome, prezzo_attuale, prezzo_orig, proprietario, "tipoImmobile", tipo_annuncio) VALUES (3, 'Bilocale appena ristrutturato, completamente arredato.', 'Viale Monza 102, Milano', 65, 'Bilocale Moderno', 800, 900, 'Mario Rossi', 'Appartamento', 'AFFITTO');
INSERT INTO public.immobile ("idImmobile", descrizione, indirizzo, metri_quadri, nome, prezzo_attuale, prezzo_orig, proprietario, "tipoImmobile", tipo_annuncio) VALUES (4, 'Luminoso ufficio open space in zona direzionale.', 'Centro Direzionale Isola, Napoli', 90, 'Ufficio Open Space', 1500, 1500, 'Mario Rossi', 'Ufficio', 'AFFITTO');
INSERT INTO public.immobile ("idImmobile", descrizione, indirizzo, metri_quadri, nome, prezzo_attuale, prezzo_orig, proprietario, "tipoImmobile", tipo_annuncio) VALUES (5, 'Affascinante casale nelle colline toscane. Prezzo base asta.', 'Strada Provinciale 12, Firenze', 300, 'Casale Storico', 150000, 150000, 'Mario Rossi', 'Villa', 'ASTA');
INSERT INTO public.immobile ("idImmobile", descrizione, indirizzo, metri_quadri, nome, prezzo_attuale, prezzo_orig, proprietario, "tipoImmobile", tipo_annuncio) VALUES (6, 'Ex fabbrica convertita in loft. Soffitti alti 5 metri.', 'Via Tortona 50, Torino', 110, 'Loft Industriale', 310000, 320000, 'Mario Rossi', 'Loft', 'VENDITA');


--
-- TOC entry 3343 (class 0 OID 24602)
-- Dependencies: 216
-- Data for Name: recensione; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 3337 (class 0 OID 24578)
-- Dependencies: 210
-- Data for Name: utente; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.utente ("idUtente", email, password, ruolo, cognome, nome, telefono, bannato) VALUES (1, 'admin@easyhousing.com', 'admin123', 'ADMIN', 'Super', 'Admin', '3330000000', false);
INSERT INTO public.utente ("idUtente", email, password, ruolo, cognome, nome, telefono, bannato) VALUES (2, 'venditore@easyhousing.com', 'venditore123', 'VENDITORE', 'Rossi', 'Mario', '3331112222', false);
INSERT INTO public.utente ("idUtente", email, password, ruolo, cognome, nome, telefono, bannato) VALUES (3, 'acquirente@easyhousing.com', 'acquirente123', 'ACQUIRENTE', 'Bianchi', 'Giulia', '3339998888', false);


--
-- TOC entry 3351 (class 0 OID 0)
-- Dependencies: 213
-- Name: asta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.asta_id_seq', 1, false);


--
-- TOC entry 3352 (class 0 OID 0)
-- Dependencies: 217
-- Name: immagine_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.immagine_id_seq', 8, true);


--
-- TOC entry 3353 (class 0 OID 0)
-- Dependencies: 211
-- Name: immobile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.immobile_id_seq', 6, true);


--
-- TOC entry 3354 (class 0 OID 0)
-- Dependencies: 215
-- Name: recensione_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recensione_id_seq', 1, false);


--
-- TOC entry 3355 (class 0 OID 0)
-- Dependencies: 209
-- Name: utente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.utente_id_seq', 3, true);


--
-- TOC entry 3192 (class 2606 OID 24600)
-- Name: asta asta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asta
    ADD CONSTRAINT asta_pkey PRIMARY KEY ("idAsta");


--
-- TOC entry 3196 (class 2606 OID 24614)
-- Name: immagine immagine_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.immagine
    ADD CONSTRAINT immagine_pkey PRIMARY KEY ("idImmagine");


--
-- TOC entry 3190 (class 2606 OID 24594)
-- Name: immobile immobile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.immobile
    ADD CONSTRAINT immobile_pkey PRIMARY KEY ("idImmobile");


--
-- TOC entry 3194 (class 2606 OID 24608)
-- Name: recensione recensione_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recensione
    ADD CONSTRAINT recensione_pkey PRIMARY KEY ("idRecensione");


--
-- TOC entry 3186 (class 2606 OID 24586)
-- Name: utente ukgxvq4mjswnupehxnp35vawmo2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.utente
    ADD CONSTRAINT ukgxvq4mjswnupehxnp35vawmo2 UNIQUE (email);


--
-- TOC entry 3188 (class 2606 OID 32814)
-- Name: utente utente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.utente
    ADD CONSTRAINT utente_pkey PRIMARY KEY ("idUtente");


-- Completed on 2026-02-28 16:05:05

--
-- PostgreSQL database dump complete
--

