# Dati connessione
spring.datasource.url=jdbc:postgresql://localhost:5432/immobiliare_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

## Hibernate crea le tabelle automaticamente
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
